<template>
  <div v-if="snapshot">
    <UButton
      to="/trial-balance"
      variant="link"
      icon="i-heroicons-arrow-left"
      size="xs"
      class="mb-1 px-0"
    >
      Back to trial balance
    </UButton>
    <h1 class="text-xl font-bold mb-6">
      Trial Balance Snapshot — {{ snapshot.financialPeriodName }}
    </h1>

    <UCard class="mb-6">
      <dl class="grid grid-cols-2 sm:grid-cols-4 gap-y-3 text-sm">
        <dt class="text-gray-500">Generated at</dt>
        <dd>{{ formatDateTime(snapshot.generatedAt) }}</dd>
        <dt class="text-gray-500">Generated by</dt>
        <dd>{{ snapshot.generatedBy }}</dd>
        <dt class="text-gray-500">Total debit</dt>
        <dd class="font-semibold">{{ formatCurrency(snapshot.totalDebit) }}</dd>
        <dt class="text-gray-500">Total credit</dt>
        <dd class="font-semibold">{{ formatCurrency(snapshot.totalCredit) }}</dd>
      </dl>
    </UCard>

    <UCard>
      <template #header>
        <div class="flex items-center justify-between">
          <span class="font-semibold">Accounts</span>
          <span
            class="text-xs font-semibold"
            :class="isBalanced ? 'text-teal-600 dark:text-teal-400' : 'text-red-500'"
          >
            {{ isBalanced ? 'Balanced' : 'Out of balance' }}
          </span>
        </div>
      </template>
      <DataTable :rows="snapshot.lines" :columns="columns" />
    </UCard>
  </div>
  <div v-else class="flex justify-center py-16">
    <UIcon name="i-heroicons-arrow-path" class="w-6 h-6 animate-spin text-gray-400" />
  </div>
</template>

<script setup lang="ts">
import type { TrialBalanceResponse, TrialBalanceRowResponse } from '~/features/accounting/types'
import type { ColumnDef } from '~/shared/types'

const route = useRoute()
const api = useApi()

const snapshotId = route.params.id as string

const { data: snapshot } = await useAsyncData(`trial-balance-snapshot-${snapshotId}`, () =>
  api<TrialBalanceResponse>(`/trial-balance/snapshots/${snapshotId}`)
)

const columns: ColumnDef<TrialBalanceRowResponse>[] = [
  { key: 'accountNo', label: 'Account no.', sortable: true },
  { key: 'accountName', label: 'Account name', sortable: true },
  { key: 'totalDebit', label: 'Debit', type: 'currency', sortable: true },
  { key: 'totalCredit', label: 'Credit', type: 'currency', sortable: true },
  { key: 'balance', type: 'currency', sortable: true }
]

const isBalanced = computed(() => {
  if (!snapshot.value) return true
  return Math.abs(snapshot.value.totalDebit - snapshot.value.totalCredit) < 0.005
})
</script>
